In [1]:
# ta511 CSM data
# my data from a mat file: first 7 rows = VN lang positive. next 
#6 rows = language negative
# DI features = 104, 
# indeg features = 104
# outdeg features = 104
# Kcores features = 104
# power features = 104
# edge betweenness features = 104
import scipy.io
import numpy as np
from matplotlib.pyplot import imshow

npos=7
nneg = 6
X = scipy.io.loadmat('X_ta511.mat',struct_as_record=False)
X_total = X['X']
y=np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0])
y=y.T

#DI features
Xtemp = X_total[:,0:104] #original DI matrix
X1 = Xtemp[0:npos,0:52]
X2 = Xtemp[0:npos,52:104]
Xnew = np.concatenate((X2,X1),axis=1) #interchange the node order
X1n = Xtemp[npos:npos+nneg,0:52]
X2n = Xtemp[npos:npos+nneg,52:104]
Xnew_n = np.concatenate((X2n,X1n),axis=1) #interchange the node order
XDI = np.concatenate((Xnew,Xtemp,Xnew_n),axis=0) #augmented DI matrix
print(XDI.shape)

#indeg features
Xtemp = X_total[:,104:208]
X1 = Xtemp[0:npos,0:52]
X2 = Xtemp[0:npos,52:104]
Xnew = np.concatenate((X2,X1),axis=1) #interchange the node order
X1n = Xtemp[npos:npos+nneg,0:52]
X2n = Xtemp[npos:npos+nneg,52:104]
Xnew_n = np.concatenate((X2n,X1n),axis=1) #interchange the node order
X_indeg = np.concatenate((Xnew,Xtemp,Xnew_n),axis=0) #augmented matrix

#outdeg features
Xtemp = X_total[:,208:312]
X1 = Xtemp[0:npos,0:52]
X2 = Xtemp[0:npos,52:104]
Xnew = np.concatenate((X2,X1),axis=1) #interchange the node order
X1n = Xtemp[npos:npos+nneg,0:52]
X2n = Xtemp[npos:npos+nneg,52:104]
Xnew_n = np.concatenate((X2n,X1n),axis=1) #interchange the node order
X_outdeg = np.concatenate((Xnew,Xtemp,Xnew_n),axis=0) #augmented matrix

#indeg and outdeg features combined
X_in_out_deg = np.concatenate((X_indeg,X_outdeg),axis=1)

#Kcores features
Xtemp = X_total[:,312:416]
X1 = Xtemp[0:npos,0:52]
X2 = Xtemp[0:npos,52:104]
Xnew = np.concatenate((X2,X1),axis=1) #interchange the node order
X1n = Xtemp[npos:npos+nneg,0:52]
X2n = Xtemp[npos:npos+nneg,52:104]
Xnew_n = np.concatenate((X2n,X1n),axis=1) #interchange the node order
X_kcores = np.concatenate((Xnew,Xtemp,Xnew_n),axis=0) #augmented matrix

#power features
Xtemp = X_total[:,416:520]
X1 = Xtemp[0:npos,0:52]
X2 = Xtemp[0:npos,52:104]
Xnew = np.concatenate((X2,X1),axis=1) #interchange the node order
X1n = Xtemp[npos:npos+nneg,0:52]
X2n = Xtemp[npos:npos+nneg,52:104]
Xnew_n = np.concatenate((X2n,X1n),axis=1) #interchange the node order
X_power = np.concatenate((Xnew,Xtemp,Xnew_n),axis=0) #augmented matrix

#edge features
Xtemp = X_total[:,520:624]
X1 = Xtemp[0:npos,0:52]
X2 = Xtemp[0:npos,52:104]
Xnew = np.concatenate((X2,X1),axis=1) #interchange the node order
X1n = Xtemp[npos:npos+nneg,0:52]
X2n = Xtemp[npos:npos+nneg,52:104]
Xnew_n = np.concatenate((X2n,X1n),axis=1) #interchange the node order
X_edge = np.concatenate((Xnew,Xtemp,Xnew_n),axis=0) #augmented matrix

#kcores and edge features combined
X_kcores_edge = np.concatenate((X_kcores,X_edge),axis=1)

#kcores and power combined
X_kcores_power = np.concatenate((X_kcores,X_power),axis=1)

#Edge and power combined
X_edge_power = np.concatenate((X_edge,X_power),axis=1)

#kcores+ edge + power combined
X_kcores_edge_power = np.concatenate((X_kcores_edge,X_power),axis=1)

#In + power combined
X_In_power = np.concatenate((X_indeg,X_power),axis=1)

#Out + power combined
X_Out_power = np.concatenate((X_outdeg,X_power),axis=1)

#InOut + power combined
X_InOut_power = np.concatenate((X_in_out_deg,X_power),axis=1)

# Inout+Kcores+power
X_InOut_kcores_power = np.concatenate((X_in_out_deg,X_kcores_power),axis=1)

nElements,pFeatures = X_kcores_edge_power.shape

print(X_kcores_edge_power.shape)
#imshow(X_power)
#plt.show()

(26, 104)
(26, 312)


In [2]:
# original Code source: Gaël Varoquaux
#              Andreas Müller
# Modified for classification for CSM data by Sudha Yellapantula
# License: BSD 3 clause
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import KFold,StratifiedKFold # import KFold
from sklearn import linear_model
from sklearn.metrics import balanced_accuracy_score, average_precision_score, precision_score, recall_score,confusion_matrix

names = ["Nearest Neighbors", "Linear SVM", "RBF SVM", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "QDA"]
nClassifiers = 4
nDataSets = 11
maxRep=100
n_splits=5

predictions = np.zeros((nClassifiers,nDataSets, nElements, maxRep))
prec = np.zeros((nClassifiers,nDataSets,n_splits,maxRep))
recall = np.zeros((nClassifiers,nDataSets,n_splits,maxRep))
bal_acc = np.zeros((nClassifiers,nDataSets,n_splits,maxRep))
tnr = np.zeros((nClassifiers,nDataSets,n_splits,maxRep))
for indRep in range(0,maxRep):

    classifiers = [
       KNeighborsClassifier(3),
        LinearSVC(C=0.00001, class_weight='balanced', dual=True, fit_intercept=False,
         intercept_scaling=1, loss='squared_hinge', max_iter=10000,
         multi_class='ovr', penalty='l2', random_state=None, tol=0.0000001,
         verbose=0),
        GaussianProcessClassifier(1.0 * RBF(1.0),random_state=None),
        DecisionTreeClassifier(max_depth=20,random_state=None)
    ]

    Power_features = (X_power,y)
    Indeg_features = (X_indeg,y)
    Outdeg_features = (X_outdeg,y)
    In_out_deg_features = (X_in_out_deg,y)
    Kcores_features = (X_kcores,y)
    Kcores_power_features = (X_kcores_power,y)
    In_power_features = (X_In_power,y)
    Out_power_features = (X_Out_power,y)
    InOut_power_features = (X_InOut_power,y)
    Kcores_In_Out_power_features = (X_InOut_kcores_power,y)

    datasets = [Power_features,
                Indeg_features,
                Outdeg_features,
                In_out_deg_features,
                Kcores_features,
                Kcores_power_features,
                In_power_features,
                Out_power_features,
                InOut_power_features,
                Kcores_In_Out_power_features
                ]



    #predictions = np.zeros((len(classifiers),len(datasets), nElements))
    kf = StratifiedKFold(n_splits=5,random_state=None, shuffle=True)
    ic,ids,ie=0,0,0 #counter index for classifier, dataset and element

    # iterate over classifiers
    for name, clf in zip(names, classifiers):
        # iterate over datasets
        ids=0
        for ds_cnt, ds in enumerate(datasets):
            # preprocess dataset, split into training and test part
            X, y = ds
            X = StandardScaler().fit_transform(X)

            ie=0
            for train_index, test_index in kf.split(X,y):
                X_train, X_test = X[train_index,:], X[test_index,:]
                y_train, y_test = y[train_index], y[test_index]

                clf.fit(X_train, y_train)
                score = clf.score(X_test, y_test)
                #predictions[ic,ids,ie,indRep]=score
                y_pred = clf.predict(X_test)
                CM = confusion_matrix(y_test, y_pred)
                TN = CM[0][0]
                FN = CM[1][0]
                TP = CM[1][1]
                FP = CM[0][1]
                bal_acc[ic,ids,ie,indRep]= balanced_accuracy_score(y_test, y_pred)
                prec[ic,ids,ie,indRep]= precision_score(y_test, y_pred)
                recall[ic,ids,ie,indRep]= recall_score(y_test, y_pred)
                tnr[ic,ids,ie,indRep]= np.true_divide(TN, (TN + FP))
                ie +=1
            ids +=1
        ic +=1




/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/

/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sudhayellapantula/opt/anaconda3/envs/langCSM/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [3]:
#for each rep, calculate these parameters
np.set_printoptions(precision=3)
prec_final = np.zeros((len(datasets),len(classifiers)))
tnrate = np.zeros((len(datasets),len(classifiers)))
rec = np.zeros((len(datasets),len(classifiers)))
acc = np.zeros((len(datasets),len(classifiers)))


ste_prec = np.zeros((len(datasets),len(classifiers)))
ste_tnrate = np.zeros((len(datasets),len(classifiers)))
ste_rec = np.zeros((len(datasets),len(classifiers)))
ste_acc = np.zeros((len(datasets),len(classifiers)))

for i in range(0,len(datasets)):
    for j in range(0,len(classifiers)):
        tnrate[i,j] = np.mean(tnr[j,i,:,:])
        prec_final[i,j] = np.mean(prec[j,i,:,:])
        rec[i,j] = np.mean(recall[j,i,:,:])
        acc[i,j] = np.mean(bal_acc[j,i,:,:])
        
for i in range(0,len(datasets)):
    for j in range(0,len(classifiers)):     
        ste_tnrate[i,j] = 1.96*np.true_divide(np.std(tnr[j,i,:,:]),np.sqrt(maxRep*n_splits))
        ste_prec[i,j] = 1.96*np.true_divide(np.std(prec[j,i,:,:]),np.sqrt(maxRep*n_splits))
        ste_rec[i,j] = 1.96*np.true_divide(np.std(recall[j,i,:,:]),np.sqrt(maxRep*n_splits))
        ste_acc[i,j] = 1.96*np.true_divide(np.std(bal_acc[j,i,:,:]),np.sqrt(maxRep*n_splits))

    

print("mean accuracy\n",acc)
print("ste of accuracy\n",ste_acc)
print("mean precision\n",prec_final)
print("ste of precision\n",ste_prec)
print("mean recall\n",rec)
print("ste of recall\n",ste_rec)
print("mean tnr/specificity\n",tnrate)
print("ste of tnr/specificity\n",ste_tnrate)






mean accuracy
 [[0.669 0.663 0.842 0.75 ]
 [0.714 0.775 0.704 0.72 ]
 [0.724 0.764 0.702 0.638]
 [0.709 0.771 0.765 0.627]
 [0.78  0.67  0.73  0.767]
 [0.719 0.721 0.836 0.732]
 [0.662 0.745 0.699 0.693]
 [0.69  0.777 0.776 0.669]
 [0.726 0.749 0.779 0.644]
 [0.756 0.751 0.778 0.665]]
ste of accuracy
 [[0.017 0.018 0.014 0.021]
 [0.016 0.012 0.017 0.017]
 [0.013 0.013 0.015 0.017]
 [0.013 0.012 0.016 0.018]
 [0.014 0.019 0.017 0.017]
 [0.015 0.015 0.012 0.02 ]
 [0.014 0.013 0.017 0.02 ]
 [0.016 0.013 0.014 0.019]
 [0.015 0.012 0.013 0.019]
 [0.013 0.013 0.013 0.019]]
mean precision
 [[0.715 0.743 0.887 0.788]
 [0.808 0.918 0.79  0.752]
 [0.808 0.888 0.777 0.682]
 [0.797 0.91  0.841 0.656]
 [0.87  0.714 0.827 0.824]
 [0.805 0.823 0.971 0.777]
 [0.734 0.878 0.767 0.725]
 [0.754 0.904 0.903 0.713]
 [0.807 0.871 0.901 0.681]
 [0.874 0.876 0.886 0.708]]
ste of precision
 [[0.029 0.026 0.017 0.023]
 [0.03  0.024 0.026 0.019]
 [0.035 0.028 0.028 0.022]
 [0.033 0.025 0.023 0.022]
 [0.029 0.035

In [4]:
#Repeat these calculations with shuffled labels to estimate significance of results
